// export const BASE_URL = "https://dev-api.unisouk.com";

import { IncompleteFormState } from "./type/feedback-form";
import { Option } from "./ui/MultiSelexctComp";

export const Countries: {
  id: string;
  name: string;
}[] = [
  { id: "AF", name: "Afghanistan" },
  { id: "AL", name: "Albania" },
  { id: "DZ", name: "Algeria" },
  { id: "AD", name: "Andorra" },
  { id: "AO", name: "Angola" },
  { id: "AR", name: "Argentina" },
  { id: "AM", name: "Armenia" },
  { id: "AU", name: "Australia" },
  { id: "AT", name: "Austria" },
  { id: "AZ", name: "Azerbaijan" },
  { id: "BH", name: "Bahrain" },
  { id: "BD", name: "Bangladesh" },
  { id: "BY", name: "Belarus" },
  { id: "BE", name: "Belgium" },
  { id: "BT", name: "Bhutan" },
  { id: "BO", name: "Bolivia" },
  { id: "BR", name: "Brazil" },
  { id: "BN", name: "Brunei" },
  { id: "BG", name: "Bulgaria" },
  { id: "KH", name: "Cambodia" },
  { id: "CA", name: "Canada" },
  { id: "CL", name: "Chile" },
  { id: "CN", name: "China" },
  { id: "CO", name: "Colombia" },
  { id: "CR", name: "Costa Rica" },
  { id: "HR", name: "Croatia" },
  { id: "CU", name: "Cuba" },
  { id: "CY", name: "Cyprus" },
  { id: "CZ", name: "Czechia" },
  { id: "DK", name: "Denmark" },
  { id: "DJ", name: "Djibouti" },
  { id: "DM", name: "Dominica" },
  { id: "DO", name: "Dominican Republic" },
  { id: "EC", name: "Ecuador" },
  { id: "EG", name: "Egypt" },
  { id: "SV", name: "El Salvador" },
  { id: "EE", name: "Estonia" },
  { id: "ET", name: "Ethiopia" },
  { id: "FJ", name: "Fiji" },
  { id: "FI", name: "Finland" },
  { id: "FR", name: "France" },
  { id: "GE", name: "Georgia" },
  { id: "DE", name: "Germany" },
  { id: "GH", name: "Ghana" },
  { id: "GR", name: "Greece" },
  { id: "GT", name: "Guatemala" },
  { id: "HT", name: "Haiti" },
  { id: "HN", name: "Honduras" },
  { id: "HU", name: "Hungary" },
  { id: "IS", name: "Iceland" },
  { id: "IN", name: "India" },
  { id: "ID", name: "Indonesia" },
  { id: "IR", name: "Iran" },
  { id: "IQ", name: "Iraq" },
  { id: "IE", name: "Ireland" },
  { id: "IL", name: "Israel" },
  { id: "IT", name: "Italy" },
  { id: "JM", name: "Jamaica" },
  { id: "JP", name: "Japan" },
  { id: "JO", name: "Jordan" },
  { id: "KZ", name: "Kazakhstan" },
  { id: "KE", name: "Kenya" },
  { id: "KW", name: "Kuwait" },
  { id: "LA", name: "Laos" },
  { id: "LV", name: "Latvia" },
  { id: "LB", name: "Lebanon" },
  { id: "LT", name: "Lithuania" },
  { id: "LU", name: "Luxembourg" },
  { id: "MG", name: "Madagascar" },
  { id: "MY", name: "Malaysia" },
  { id: "MV", name: "Maldives" },
  { id: "MT", name: "Malta" },
  { id: "MX", name: "Mexico" },
  { id: "MN", name: "Mongolia" },
  { id: "MA", name: "Morocco" },
  { id: "MM", name: "Myanmar" },
  { id: "NP", name: "Nepal" },
  { id: "NL", name: "Netherlands" },
  { id: "NZ", name: "New Zealand" },
  { id: "NI", name: "Nicaragua" },
  { id: "NG", name: "Nigeria" },
  { id: "NO", name: "Norway" },
  { id: "OM", name: "Oman" },
  { id: "PK", name: "Pakistan" },
  { id: "PA", name: "Panama" },
  { id: "PY", name: "Paraguay" },
  { id: "PE", name: "Peru" },
  { id: "PH", name: "Philippines" },
  { id: "PL", name: "Poland" },
  { id: "PT", name: "Portugal" },
  { id: "QA", name: "Qatar" },
  { id: "RO", name: "Romania" },
  { id: "RU", name: "Russia" },
  { id: "RW", name: "Rwanda" },
  { id: "SA", name: "Saudi Arabia" },
  { id: "SN", name: "Senegal" },
  { id: "RS", name: "Serbia" },
  { id: "SG", name: "Singapore" },
  { id: "SK", name: "Slovakia" },
  { id: "SI", name: "Slovenia" },
  { id: "SO", name: "Somalia" },
  { id: "ZA", name: "South Africa" },
  { id: "KR", name: "South Korea" },
  { id: "ES", name: "Spain" },
  { id: "LK", name: "Sri Lanka" },
  { id: "SD", name: "Sudan" },
  { id: "SE", name: "Sweden" },
  { id: "CH", name: "Switzerland" },
  { id: "SY", name: "Syria" },
  { id: "TW", name: "Taiwan" },
  { id: "TJ", name: "Tajikistan" },
  { id: "TZ", name: "Tanzania" },
  { id: "TH", name: "Thailand" },
  { id: "TN", name: "Tunisia" },
  { id: "TR", name: "Turkey" },
  { id: "UG", name: "Uganda" },
  { id: "UA", name: "Ukraine" },
  { id: "AE", name: "United Arab Emirates" },
  { id: "GB", name: "United Kingdom" },
  { id: "US", name: "United States" },
  { id: "UY", name: "Uruguay" },
  { id: "UZ", name: "Uzbekistan" },
  { id: "VE", name: "Venezuela" },
  { id: "VN", name: "Vietnam" },
  { id: "YE", name: "Yemen" },
  { id: "ZM", name: "Zambia" },
  { id: "ZW", name: "Zimbabwe" },
];

export const CHANNEL_NAME: Record<string, string> = {
  ONDC: "ONDC",
  AMAZON_IN: "AMAZON",
  WOOCOMMERCE: "WOOCOMMERCE",
  SHOPIFY: "SHOPIFY",
  WIX: "WIX",
};

export const CHANNEL_NAME_LOWERCASE: Record<string, string> = {
  ONDC: "ondc",
  AMAZON_IN: "amazon",
  WOOCOMMERCE: "woocommerce",
  SHOPIFY: "shopify",
  WIX: "wix",
};

export const CHANNEL_LABELS = {
  ONDC: "ONDC",
  WOOCOMMERCE: "WooCommerce",
  SHOPIFY: "Shopify",
  WIX: "Wix",
  AMAZON_IN: "Amazon",
  AMAZON: "Amazon",
  DEFAULT: "Default",
};

export const PRODUCT_MAPPED_ARRRIBUTES: Record<string, string> = {
  size: "Size",
  color: "Color",
  flavor: "Flavor",
  scent: "Scent",
  numberOfItems: "Number of Items",
  itemWeight: "Item Weight",
};

export const stuckOptions: Option[] = [
  { label: "Didn’t understand the required fields", value: "requiredFields" },
  { label: "Faced a validation error", value: "validationError" },
  { label: "Images failed to upload", value: "imagesFail" },
  { label: "Price or stock field was confusing", value: "priceStock" },
  { label: "Category/variant fields were complex", value: "categoryVariant" },
  { label: "Page got stuck or was slow", value: "pageSlow" },
  { label: "Something else", value: "other" },
];

export const preventedOptions: Option[] = [
  { label: "Form was too long", value: "tooLong" },
  { label: "Fields were unclear", value: "fieldsUnclear" },
  { label: "Technical issue / Bug", value: "technicalIssue" },
  { label: "Didn’t have the required information", value: "noInfo" },
  { label: "Gave up / Felt overwhelming", value: "gaveUp" },
  { label: "Other", value: "other" },
];

export const stopStepOptions: Option[] = [
  { label: "Basic info", value: "basicInfo" },
  { label: "Category & attributes", value: "category" },
  { label: "Pricing", value: "pricing" },
  { label: "Images", value: "images" },
  { label: "Inventory", value: "inventory" },
  { label: "Variants", value: "variants" },
  { label: "Manufacturing", value: "manufacturing" },
  { label: "Package", value: "package" },
  { label: "Publishing Channels", value: "publishingChannels" },
  { label: "Don’t remember", value: "dontRemember" },
];

export const completionHelpOptions: Option[] = [
  { label: "Clear examples", value: "clearExamples" },
  { label: "Tooltips or hints", value: "tooltips" },
  { label: "Fewer required fields", value: "fewerFields" },
  { label: "Auto-fill options", value: "autofill" },
  { label: "Better explanation of pricing", value: "pricingExplanation" },
  { label: "Faster load time", value: "fasterLoad" },
  { label: "A step-by-step guide", value: "stepByStep" },
  { label: "Chat support / Help center", value: "chatSupport" },
  { label: "Other", value: "other" },
];

export const deviceOptions: Option[] = [
  { label: "Mobile", value: "mobile" },
  { label: "Desktop", value: "desktop" },
  { label: "Tablet", value: "tablet" },
];

export const initialFormState: IncompleteFormState = {
  gotStuck: [],
  stuckReason: "",
  prevented: null,
  preventedReason: "",
  anyError: null,
  errorDescription: "",
  difficulty: 0,
  stoppedStep: null,
  neededHelp: [],
  neededHelpReason: "",
  device: null,
  suggestion: "",
};
